Repository S010MON/multi-agent-surveillance, pull requests merged in 2022-03, with the labels that each got.

#167 Agent-agent vision
  src/main/java/app/controller/graphicsEngine/RayTracing.java
  src/main/java/app/controller/linAlg/Intersection.java
  src/main/java/app/model/agents/Agent.java
  src/main/java/app/model/agents/AgentImp.java
  src/test/java/testing/AgentVisionTest.java
Labels: MEDIUM

#171 Portal to file
  src/main/java/app/view/mapBuilder/DisplayPane.java
  src/main/java/app/view/mapBuilder/FurniturePane.java
  src/main/java/app/view/mapBuilder/MbObject.java
  src/main/java/app/view/mapBuilder/StartMenu.java
Labels: bug

#175 Map builder refactor
  src/main/java/app/view/mapBuilder/FurniturePane.java
  src/main/java/app/view/mapBuilder/SettingsPane.java
  src/main/java/app/view/mapBuilder/StartMenu.java
Labels: refactor

#243 Display walls "seen"
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/model/Map.java
  src/main/java/app/view/simulation/Renderer.java
Labels: LOW
