Repository S010MON/multi-agent-surveillance, pull requests merged in 2022-04, with the labels that each got.

#256 goal-direction
  src/main/java/app/model/Map.java
  src/main/java/app/model/agents/Agent.java
  src/main/java/app/model/agents/AgentImp.java
  src/main/java/app/model/agents/WallFollow/WallFollowAgent.java
Labels: MEDIUM, Lvl 1

#260 Aco label obstacles
  src/main/java/app/model/agents/ACO/AcoAgent.java
  src/main/java/app/model/agents/AgentImp.java
  src/main/java/app/model/agents/MemoryGraph.java
  src/main/resources/teleportMap.txt
  src/test/java/testing/AcoAgentTesting.java
  src/test/java/testing/MemoryGraphTesting.java
Labels: Lvl 1

#266 Sound engine refactor
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/controller/graphicsEngine/GraphicsEngine.java
  src/main/java/app/controller/graphicsEngine/Ray.java
  src/main/java/app/controller/linAlg/Intersection.java
  src/main/java/app/controller/linAlg/Line.java
  src/main/java/app/controller/linAlg/Vector.java
  src/main/java/app/controller/soundEngine/CornerAimedTracing.java
  src/main/java/app/controller/soundEngine/Sound.java
  src/main/java/app/controller/soundEngine/SoundEngine.java
  src/main/java/app/controller/soundEngine/SoundRay.java
  src/main/java/app/controller/soundEngine/SoundRayScatter.java
  src/main/java/app/controller/soundEngine/SoundVector.java
  src/main/java/app/model/Coverage.java
  src/main/java/app/model/Map.java
  src/main/java/app/model/agents/ACO/AcoAgent.java
  src/main/java/app/model/agents/Agent.java
  src/main/java/app/model/agents/AgentImp.java
  src/main/java/app/model/agents/WallFollow/WallFollowAgent.java
  src/main/java/app/model/boundary/BoundaryFactory.java
  src/main/java/app/model/furniture/Furniture.java
  src/main/java/app/model/furniture/FurnitureBase.java
  src/main/java/app/model/furniture/FurnitureFactory.java
  src/main/java/app/model/sound/SoundBoundary.java
  src/main/java/app/model/sound/SoundBoundaryFactory.java
  src/main/java/app/model/sound/SoundBoundaryImp.java
  src/main/java/app/model/sound/SoundSource.java
  src/main/java/app/model/soundBoundary/TransmittingBoundary.java
  src/main/java/app/model/soundFurniture/SoundFurniture.java
  src/main/java/app/model/soundFurniture/SoundFurnitureBase.java
  src/main/java/app/model/soundFurniture/SoundFurnitureFactory.java
  src/main/java/app/model/soundSource/SoundSource.java
  src/main/java/app/model/soundSource/SoundSourceBase.java
  src/main/java/app/model/soundSource/SoundSourceFactory.java
  src/main/java/app/model/soundSource/SoundSourceType.java
  src/main/java/app/view/mapBuilder/DisplayPane.java
  src/main/java/app/view/simulation/Renderer.java
  src/main/resources/map_1.txt
  src/test/java/testing/IntersectionTest.java
  src/test/java/testing/SoundBoundaryTest.java
  src/test/java/testing/SoundEngineTest.java
  src/test/java/testing/SoundFurnitureTest.java
  src/test/java/testing/SoundSourceTest.java
Labels: refactor

#267 Agent State Change
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/model/Map.java
  src/main/java/app/model/agents/Agent.java
  src/main/java/app/model/agents/AgentImp.java
Labels: MEDIUM, Lvl 4

#270 Agent team feedback from ray
  src/main/java/app/controller/graphicsEngine/GraphicsEngine.java
  src/main/java/app/controller/graphicsEngine/Ray.java
  src/main/java/app/controller/linAlg/AgentIntersection.java
  src/main/java/app/model/Map.java
  src/test/java/testing/RayFeedbackTest.java
Labels: HIGH, Lvl 2

#294 patches bug #293
  src/main/java/app/controller/linAlg/Intersection.java
  src/main/java/app/controller/soundEngine/SoundEngine.java
  src/main/java/app/model/Map.java
Labels: bug
