Repository S010MON/multi-agent-surveillance, pull requests merged in 2022-05, with the labels that each got.

#302 "Fixes null pointer exception when agent teleports"
  src/main/java/app/model/agents/ACO/AcoAgent.java
Labels: bug

#305 304 aco varients for testing
  src/main/java/app/model/Map.java
  src/main/java/app/model/agents/ACO/AcoAgent.java
  src/main/java/app/model/agents/ACO/AcoColony.java
  src/main/java/app/model/agents/ACO/AcoMid.java
  src/main/java/app/model/agents/ACO/AcoMomentum.java
  src/main/java/app/model/agents/ACO/AcoMomentumSpiralAvoidance.java
  src/main/java/app/model/agents/ACO/AcoRanking.java
  src/test/java/testing/AcoAgentTesting.java
  src/test/java/testing/AcoRankingTesting.java
Labels: HIGH

#309 Static Methods for angle normalization
  src/main/java/app/controller/linAlg/Angle.java
  src/test/java/testing/AngleTest.java
Labels: refactor

#317 #316 Fixed. One line change.
  src/main/java/app/view/mapBuilder/SettingsPane.java
Labels: bug

#321 #320 Checking ray for Feedback.
  src/main/java/app/model/agents/Agent.java
  src/main/java/app/model/agents/AgentImp.java
Labels: Lvl 1

#318 Headless Agent Testing
  src/test/java/testing/HeadlessAgentTest.java
Labels: Lvl 2

#322 Dynamic experimentation framework to allow variant experimentation
  src/main/java/app/model/Map.java
  src/main/java/app/model/Type.java
  src/main/java/app/model/agents/AgentType.java
  src/test/java/experiments/Experiments.java
  src/test/java/testing/WallFollowAgentTest.java
Labels: HIGH

#289 Agent capture imp
  src/main/java/app/model/agents/AgentImp.java
  src/main/java/app/model/agents/Capture/Capture.java
  src/main/resources/TestCapture
  src/test/java/testing/CaptureAgentTest.java
Labels: HIGH

#308 Bug vision doesnt detect agents
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/controller/graphicsEngine/GraphicsEngine.java
  src/main/java/app/controller/linAlg/Intersection.java
  src/main/java/app/model/agents/AgentImp.java
  src/main/java/app/model/agents/Universe.java
  src/main/resources/AcoTestMap
  src/test/java/testing/AcoAgentTesting.java
  src/test/java/testing/AcoRankingTesting.java
  src/test/java/testing/RayFeedbackTest.java
Labels: bug

#343 removed TargetBoundaries from getBoundaries in Map
  src/main/java/app/model/Map.java
Labels: bug, HIGH

#337 274 user interface viewrays
  src/main/java/app/App.java
  src/main/java/app/view/FileMenuBar.java
  src/main/java/app/view/simulation/Renderer.java
  src/main/java/app/view/simulation/Simulation.java
Labels: LOW

#347 334 agent cannot move through flag
  src/main/java/app/model/boundary/Flag.java
  src/main/java/app/model/boundary/TargetBoundary.java
  src/main/java/app/view/Alert.java
  src/main/java/app/view/mapBuilder/StartMenu.java
Labels: bug

#339 #338 File name chosen by user when creating map
  src/main/java/app/view/Alert.java
  src/main/java/app/view/mapBuilder/StartMenu.java
Labels: refactor
