Repository S010MON/multi-agent-surveillance, pull requests merged in 2022-02, with the labels that each got.

#19 Ray drawing
  build.gradle
  src/main/java/app/App.java
  src/main/java/app/view/Frame.java
  src/main/java/app/view/Renderer.java
  src/main/java/jgfx/javagradlefx/HelloApplication.java
  src/main/java/jgfx/javagradlefx/HelloController.java
  src/main/java/module-info.java
  src/main/resources/jgfx/javagradlefx/hello-view.fxml
Labels: enhancement

#20 Class ray
  build.gradle
  settings.gradle
  src/main/java/app/controller/Ray.java
  src/main/java/app/controller/Vector.java
  src/test/java/jgfx/javagradlefx/RayTest.java
  src/test/java/jgfx/javagradlefx/VectorTest.java
Labels: enhancement

#22 Renderer draw rays
  src/main/java/app/controller/Ray.java
  src/main/java/app/controller/RotationMatrix.java
  src/main/java/app/controller/Vector.java
  src/main/java/app/view/Renderer.java
  src/test/java/jgfx/javagradlefx/RayTest.java
Labels: enhancement

#25 Adds Placeable and Agent interfaces
  src/main/java/app/model/Agent.java
  src/main/java/app/model/Placeable.java
Labels: enhancement

#27 Class agent imp
  src/main/java/app/App.java
  src/main/java/app/controller/AgentImp.java
  src/main/java/app/controller/Beam.java
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/controller/GraphicsEngine.java
  src/main/java/app/controller/Ray.java
  src/main/java/app/controller/RayTracing.java
  src/main/java/app/controller/RotationMatrix.java
  src/main/java/app/controller/Vector.java
  src/main/java/app/model/Agent.java
  src/main/java/app/model/Border.java
  src/main/java/app/model/MapTemp.java
  src/main/java/app/model/Placeable.java
  src/main/java/app/model/Wall.java
  src/main/java/app/view/Frame.java
  src/main/java/app/view/Renderer.java
  src/test/java/jgfx/javagradlefx/AgentImpTest.java
  src/test/java/jgfx/javagradlefx/BeamTest.java
  src/test/java/jgfx/javagradlefx/BorderTest.java
  src/test/java/jgfx/javagradlefx/VectorTest.java
Labels: enhancement

#35 Settings object
  src/main/java/app/controller/Settings.java
  src/main/java/module-info.java
Labels: enhancement

#36 Fixes ray tracing bug
  src/main/java/app/controller/RayTracing.java
  src/main/java/app/model/Border.java
  src/main/java/app/model/MapTemp.java
Labels: bug

#40 adds movement component to Human
  src/main/java/app/App.java
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/controller/Human.java
  src/main/java/app/controller/ManualAgent.java
  src/main/java/app/model/MapTemp.java
  src/main/java/app/view/Frame.java
Labels: enhancement

#53 File parsing
  src/main/java/app/controller/FileParser.java
  src/test/java/jgfx/javagradlefx/FileParserTest.java
  src/test/java/jgfx/javagradlefx/mytest.txt
Labels: enhancement

#60 Changing to javafx rectangle2d
  src/main/java/app/controller/FileParser.java
  src/main/java/app/controller/Settings.java
  src/main/java/app/model/Map.java
Labels: enhancement

#61 Shaded areas
  src/main/java/app/controller/graphicsEngine/RayTracing.java
  src/main/java/app/model/Furniture.java
  src/main/java/app/model/Map.java
  src/main/java/app/model/agents/Agent.java
  src/main/java/app/model/boundary/Boundary.java
  src/main/java/app/model/boundary/BoundaryFactory.java
  src/main/java/app/model/boundary/Placeable.java
  src/main/java/app/model/boundary/VisibleBoundary.java
  src/main/java/app/model/texture/Shade.java
  src/main/java/app/model/texture/Texture.java
  src/main/java/app/model/texture/TextureFactory.java
  src/main/java/app/model/texture/Wall.java
  src/main/java/app/view/Renderer.java
  src/test/java/jgfx/javagradlefx/BoundaryTest.java
Labels: enhancement

#85 File menu
  src/main/java/app/view/FileMenuBar.java
  src/main/java/app/view/Frame.java
Labels: enhancement

#95 Agent spawning
  src/main/java/app/controller/FileParser.java
  src/main/java/app/controller/Settings.java
  src/main/java/app/model/map/Map.java
  src/main/java/app/view/Renderer.java
  src/main/resources/map_1.txt
  src/main/resources/map_test.txt
  src/test/java/jgfx/javagradlefx/SaveMapTest.java
Labels: enhancement

#100 Class WallFollowAgent
  src/main/java/app/controller/graphicsEngine/Ray.java
  src/main/java/app/model/agents/WallFollowAgent.java
  src/main/java/app/model/map/Map.java
  src/test/java/jgfx/javagradlefx/WallFollowAgentTest.java
Labels: enhancement

#98 Lombok
  README.md
  STYLE_GUIDE.md
  build.gradle
  src/main/java/app/App.java
  src/main/java/app/controller/linAlg/Vector.java
  src/main/java/module-info.java
  src/test/java/testing/BoundaryTest.java
  src/test/java/testing/FileParserTest.java
  src/test/java/testing/IntersectionTest.java
  src/test/java/testing/RayScatterTest.java
  src/test/java/testing/RayTest.java
  src/test/java/testing/RayTracingTest.java
  src/test/java/testing/SaveMapTest.java
  src/test/java/testing/StreamTest.java
  src/test/java/testing/VectorTest.java
  src/test/java/testing/mytest.txt
  sshots/Lombok_annotations.png
  sshots/Lombok_plugin.png
  sshots/bliLombok.png
  sshots/imLombok.png
Labels: documentation

#106 Sprint walk speed in agents from map
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/model/agents/Agent.java
  src/main/java/app/model/agents/AgentImp.java
  src/main/java/app/model/agents/Human.java
  src/main/java/app/model/map/Map.java
  src/test/java/jgfx/javagradlefx/MapTest.java
Labels: HIGH

#110 Refactor-Repo
  src/main/java/app/controller/FileParser.java
  src/main/java/app/controller/GameEngine.java
  src/main/java/app/controller/SaveMap.java
  src/main/java/app/controller/Settings.java
  src/main/java/app/controller/graphicsEngine/FieldOfView.java
  src/main/java/app/controller/graphicsEngine/GraphicsEngine.java
  src/main/java/app/controller/graphicsEngine/RayTracing.java
  src/main/java/app/controller/io/FileManager.java
  src/main/java/app/controller/io/FileParser.java
  src/main/java/app/controller/io/FilePath.java
  src/main/java/app/controller/io/FileSaver.java
  src/main/java/app/controller/settings/Settings.java
  src/main/java/app/controller/settings/SettingsGenerator.java
  src/main/java/app/controller/settings/SettingsObject.java
  src/main/java/app/model/Map.java
  src/main/java/app/model/boundary/BoundaryFactory.java
  src/main/java/app/model/furniture/FurnitureType.java
  src/main/java/app/view/AcoFrame.java
  src/main/java/app/view/Frame.java
  src/main/java/app/view/Renderer.java
  src/main/resources/map_1.txt
  src/main/resources/map_test.txt
  src/test/java/testing/FieldOfViewTest.java
  src/test/java/testing/FileParserTest.java
  src/test/java/testing/MapTest.java
  src/test/java/testing/SaveMapTest.java
  src/test/java/testing/SaveSettingsTest.java
  src/test/java/testing/StreamTest.java
  src/test/java/testing/WallFollowAgentTest.java
  src/test/resources/map_test.txt
  src/test/resources/mytest.txt
Labels: refactor

#117 Fixed FileParserTest
  src/main/java/app/model/furniture/FurnitureType.java
  src/test/java/testing/FileParserTest.java
  src/test/resources/mytest.txt
Labels: refactor

#118 removes all the build files that seem to have leaked into project
  .gitignore
Labels: bug, documentation

#126 "Grid displays showing agent movements
  src/main/java/app/model/Grid/AcoGrid.java
  src/main/java/app/model/agents/ACO/AcoAgent.java
  src/main/java/app/model/agents/Cells/PheromoneCell.java
  src/test/java/testing/AcoGridTest.java
Labels: MEDIUM

#135 Ray tracing bug
  src/main/java/app/model/boundary/InvisibleBoundary.java
  src/test/java/testing/RayTest.java
  src/test/java/testing/RayTracingTest.java
Labels: bug

#137 intersection refactor
  src/main/java/app/controller/linAlg/Intersection.java
  src/main/java/app/model/boundary/InvisibleBoundary.java
  src/test/java/testing/IntersectionTest.java
Labels: refactor
